baseURL = 'https://deuxrecords.com/'
languageCode = 'en-us'
title = 'Deux Records'
theme = 'PaperMod'
googleAnalytics = ''

[params]
    defaultTheme = "dark" # Perfect for the analog/studio vibe
    showReadingTime = true
    displayFullContent = false
    ShowPostNavLinks = true

    [params.homeInfoParams]
        Title = "Beatmaking, Sound Design, & Crate Digging"
        Content = "refreshing."

    [params]
    # This tells PaperMod to show the icons in the footer
        ShowShareButtons = true
        ShowCodeCopyButtons = true
        hideFooter = false # Keep the footer visible for your socials
        showCopyright = true
        disableHugoGeneratorInject = true

    [[params.socialIcons]]
        name = "bandcamp"
        url = "https://plugdeux.bandcamp.com"

    [[params.socialIcons]]
        name = "youtube"
        url = "https://youtube.com/@plugdeux"

    [[params.socialIcons]]
        name = "tiktok"
        url = "https://tiktok.com/@plugdeux"
    
    [[params.socialIcons]]
        name = "instagram"
        url = "https://instagram.com/plugdeux"
