baseURL = 'https://deuxrecords.com/'
languageCode = 'en-us'
title = 'Deux Records'
theme = 'PaperMod'

[params]
    # Minimalism Settings
    defaultTheme = "dark"
    showReadingTime = false        # Removes "1 min read"
    displayFullContent = false
    ShowPostNavLinks = false       # Removes "Next/Previous Post" buttons
    ShowShareButtons = false       # Removes the FB, Reddit, etc. clutter
    ShowCodeCopyButtons = true
    
    # Footer & Credits
    hideFooter = false             # Keep this false so your icons show
    showCopyright = true
    disableHugoGeneratorInject = true
    # This is the secret for PaperMod to hide "Powered by"
    hideHTMLEndComnt = true 

    [params.homeInfoParams]
        Title = "Beatmaking, Sound Design, & Crate Digging"
        Content = "refreshing."

    [[params.socialIcons]]
        name = "bandcamp"
        url = "https://plugdeux.bandcamp.com"

    [[params.socialIcons]]
        name = "youtube"
        url = "https://youtube.com/@plugdeux"

    [[params.socialIcons]]
        name = "tiktok"
        url = "https://tiktok.com/@plugdeux"
    
    [[params.socialIcons]]
        name = "instagram"
        url = "https://instagram.com/plugdeux"